// ignore_for_file: non_constant_identifier_names, unused_import
import "package:general_lib/general_lib.dart";
// import "dart:convert";

/// Generated By General Library Documentation Undocument By General Corporation & Global Corporation & General Developer
class LoadModelFromFileLlamaLibrary extends JsonScheme {
  /// Generated By General Library Documentation Undocument By General Corporation & Global Corporation & General Developer
  LoadModelFromFileLlamaLibrary(super.rawData);

  /// return default data
  ///
  static Map get defaultData {
    return {
      "@type": "loadModelFromFileLlamaLibrary",
      "model_file_path": "",
      "@return_type": "ok",
      "@extra": ""
    };
  }

  /// check data
  /// if raw data
  /// - rawData["@type"] == loadModelFromFileLlamaLibrary
  /// if same return true
  bool json_scheme_utils_checkDataIsSameBySpecialType() {
    return rawData["@type"] == defaultData["@type"];
  }

  /// check value data whatever do yout want
  bool json_scheme_utils_checkDataIsSameBuilder({
    required bool Function(Map rawData, Map defaultData) onResult,
  }) {
    return onResult(rawData["@type"], defaultData["@type"]);
  }

  /// create [LoadModelFromFileLlamaLibrary]
  /// Empty
  static LoadModelFromFileLlamaLibrary empty() {
    return LoadModelFromFileLlamaLibrary({});
  }

  /// Generated By General Library Documentation Undocument By General Corporation & Global Corporation & General Developer
  String? get special_type {
    try {
      if (rawData["@type"] is String == false) {
        return null;
      }
      return rawData["@type"] as String;
    } catch (e) {
      return null;
    }
  }

  /// Generated By General Library Documentation Undocument By General Corporation & Global Corporation & General Developer
  set special_type(String? value) {
    rawData["@type"] = value;
  }

  /// Generated By General Library Documentation Undocument By General Corporation & Global Corporation & General Developer
  String? get model_file_path {
    try {
      if (rawData["model_file_path"] is String == false) {
        return null;
      }
      return rawData["model_file_path"] as String;
    } catch (e) {
      return null;
    }
  }

  /// Generated By General Library Documentation Undocument By General Corporation & Global Corporation & General Developer
  set model_file_path(String? value) {
    rawData["model_file_path"] = value;
  }

  /// Generated By General Library Documentation Undocument By General Corporation & Global Corporation & General Developer
  String? get special_return_type {
    try {
      if (rawData["@return_type"] is String == false) {
        return null;
      }
      return rawData["@return_type"] as String;
    } catch (e) {
      return null;
    }
  }

  /// Generated By General Library Documentation Undocument By General Corporation & Global Corporation & General Developer
  set special_return_type(String? value) {
    rawData["@return_type"] = value;
  }

  /// Generated By General Library Documentation Undocument By General Corporation & Global Corporation & General Developer
  String? get special_extra {
    try {
      if (rawData["@extra"] is String == false) {
        return null;
      }
      return rawData["@extra"] as String;
    } catch (e) {
      return null;
    }
  }

  /// Generated By General Library Documentation Undocument By General Corporation & Global Corporation & General Developer
  set special_extra(String? value) {
    rawData["@extra"] = value;
  }

  /// Generated By General Library Documentation Undocument By General Corporation & Global Corporation & General Developer
  static LoadModelFromFileLlamaLibrary create({
    bool schemeUtilsIsSetDefaultData = false,
    String special_type = "loadModelFromFileLlamaLibrary",
    String? model_file_path,
    String special_return_type = "ok",
    String special_extra = "",
  }) {
    // LoadModelFromFileLlamaLibrary loadModelFromFileLlamaLibrary = LoadModelFromFileLlamaLibrary({
    final Map loadModelFromFileLlamaLibrary_data_create_json = {
      "@type": special_type,
      "model_file_path": model_file_path,
      "@return_type": special_return_type,
      "@extra": special_extra,
    };

    loadModelFromFileLlamaLibrary_data_create_json
        .removeWhere((key, value) => value == null);

    if (schemeUtilsIsSetDefaultData) {
      defaultData.forEach((key, value) {
        if (loadModelFromFileLlamaLibrary_data_create_json.containsKey(key) ==
            false) {
          loadModelFromFileLlamaLibrary_data_create_json[key] = value;
        }
      });
    }
    return LoadModelFromFileLlamaLibrary(
        loadModelFromFileLlamaLibrary_data_create_json);
  }
}
