// ignore_for_file: non_constant_identifier_names, unused_import
import "package:general_lib/general_lib.dart";
// import "dart:convert";

/// Generated By General Library Documentation Undocument By General Corporation & Global Corporation & General Developer
class SendLlamaLibraryMessage extends JsonScheme {
  /// Generated By General Library Documentation Undocument By General Corporation & Global Corporation & General Developer
  SendLlamaLibraryMessage(super.rawData);

  /// return default data
  ///
  static Map get defaultData {
    return {
      "@type": "sendLlamaLibraryMessage",
      "text": "",
      "@return_type": "ok",
      "@extra": ""
    };
  }

  /// check data
  /// if raw data
  /// - rawData["@type"] == sendLlamaLibraryMessage
  /// if same return true
  bool json_scheme_utils_checkDataIsSameBySpecialType() {
    return rawData["@type"] == defaultData["@type"];
  }

  /// check value data whatever do yout want
  bool json_scheme_utils_checkDataIsSameBuilder({
    required bool Function(Map rawData, Map defaultData) onResult,
  }) {
    return onResult(rawData["@type"], defaultData["@type"]);
  }

  /// create [SendLlamaLibraryMessage]
  /// Empty
  static SendLlamaLibraryMessage empty() {
    return SendLlamaLibraryMessage({});
  }

  /// Generated By General Library Documentation Undocument By General Corporation & Global Corporation & General Developer
  String? get special_type {
    try {
      if (rawData["@type"] is String == false) {
        return null;
      }
      return rawData["@type"] as String;
    } catch (e) {
      return null;
    }
  }

  /// Generated By General Library Documentation Undocument By General Corporation & Global Corporation & General Developer
  set special_type(String? value) {
    rawData["@type"] = value;
  }

  /// Generated By General Library Documentation Undocument By General Corporation & Global Corporation & General Developer
  String? get text {
    try {
      if (rawData["text"] is String == false) {
        return null;
      }
      return rawData["text"] as String;
    } catch (e) {
      return null;
    }
  }

  /// Generated By General Library Documentation Undocument By General Corporation & Global Corporation & General Developer
  set text(String? value) {
    rawData["text"] = value;
  }

  /// Generated By General Library Documentation Undocument By General Corporation & Global Corporation & General Developer
  String? get special_return_type {
    try {
      if (rawData["@return_type"] is String == false) {
        return null;
      }
      return rawData["@return_type"] as String;
    } catch (e) {
      return null;
    }
  }

  /// Generated By General Library Documentation Undocument By General Corporation & Global Corporation & General Developer
  set special_return_type(String? value) {
    rawData["@return_type"] = value;
  }

  /// Generated By General Library Documentation Undocument By General Corporation & Global Corporation & General Developer
  String? get special_extra {
    try {
      if (rawData["@extra"] is String == false) {
        return null;
      }
      return rawData["@extra"] as String;
    } catch (e) {
      return null;
    }
  }

  /// Generated By General Library Documentation Undocument By General Corporation & Global Corporation & General Developer
  set special_extra(String? value) {
    rawData["@extra"] = value;
  }

  /// Generated By General Library Documentation Undocument By General Corporation & Global Corporation & General Developer
  static SendLlamaLibraryMessage create({
    bool schemeUtilsIsSetDefaultData = false,
    String special_type = "sendLlamaLibraryMessage",
    String? text,
    String special_return_type = "ok",
    String special_extra = "",
  }) {
    // SendLlamaLibraryMessage sendLlamaLibraryMessage = SendLlamaLibraryMessage({
    final Map sendLlamaLibraryMessage_data_create_json = {
      "@type": special_type,
      "text": text,
      "@return_type": special_return_type,
      "@extra": special_extra,
    };

    sendLlamaLibraryMessage_data_create_json
        .removeWhere((key, value) => value == null);

    if (schemeUtilsIsSetDefaultData) {
      defaultData.forEach((key, value) {
        if (sendLlamaLibraryMessage_data_create_json.containsKey(key) ==
            false) {
          sendLlamaLibraryMessage_data_create_json[key] = value;
        }
      });
    }
    return SendLlamaLibraryMessage(sendLlamaLibraryMessage_data_create_json);
  }
}
