name: 'llama_library'
description: "LLaMA Is Library for Inference of Meta's LLaMA model (and others)"
version: '0.0.2'
environment:
  sdk: '>=3.6.0 <4.0.0'
dependencies:
  general_lib: '^0.0.66'
  ffi: '^2.1.0'
  path: '^1.9.0'
  ffi_universe: '^0.0.6'
dev_dependencies:
  lints: '^5.0.0'
  test: 'any'
  ffigen: '^15.0.0'
dependency_overrides:
  pointycastle: '3.8.0'
  mime: '^2.0.0'
flutter:
  uses-material-design: true
funding:
  - 'https://github.com/sponsors/azkadev'
  - 'https://github.com/sponsors/generalfoss'
  - 'https://github.com/sponsors/general-developer'
homepage: 'https://www.youtube.com/@general_dev'
repository: 'https://github.com/General-Developer/llama_library'
issue_tracker: 'https://t.me/DEVELOPER_GLOBAL_PUBLIC'
documentation: 'https://www.youtube.com/@general_dev'
ffigen:
  name: 'LlamaLibrarySharedBindingsByGeneralDeveloper'
  description: 'LlamaLibrarySharedBindingsByGeneralDeveloper Binding By General Corporation & Global Corporation & General Developer'
  output: 'lib/ffi/bindings.dart'
platforms:
  android: null
  ios: null
  linux: null
  macos: null
  web: null
  windows: null
project:
  type: ''
