name: 'llama_app'
description: 'A new Flutter project.'
publish_to: 'none'
version: '1.0.0+1'
repository: 'https://github.com/General-Developer/whisper_library'
homepage: 'https://www.youtube.com/@general_dev'
issue_tracker: 'https://t.me/DEVELOPER_GLOBAL_PUBLIC'
documentation: 'https://www.youtube.com/@general_dev'
funding:
  - 'https://github.com/sponsors/General-Developer'
  - 'https://github.com/sponsors/azkadev'
  - 'https://github.com/sponsors/generalfoss'
  - 'https://github.com/sponsors/general-developer'
environment:
  sdk: '>=3.6.0 <4.0.0'
dependencies:
  cupertino_icons: '^1.0.8'
  database_universe: '^0.0.0'
  file_picker: '^9.0.2'
  flutter:
    sdk: 'flutter'
  general_universe: '^0.0.0'
  general_universe_flutter: '^0.0.0'
  ggml_library_flutter: '^0.0.10'
  llama_library: '^0.0.3'
  llama_library_flutter: '^0.0.3'
  media_universe_flutter: '^0.0.0'
  packagex: '^0.0.0'
  path: '^1.9.0'
dev_dependencies:
  build_runner: 'any'
  flutter_lints: '^5.0.0'
  flutter_test:
    sdk: 'flutter'
  msix: '^3.16.8'
flutter:
  uses-material-design: true
project:
  type: ''
  is_use_direct_package: false
  is_private: false
  developers:
    - username: ''
      note: ''
      social_medias:
        - 'https://github.com'
dependency_overrides:
  mime: '^2.0.0'
  pointycastle: '^4.0.0'
packagex:
  name: 'llama_app'
  is_without_platform_name: true
  is_app_auto_clean_up_folder: true
  flutter_build_arguments:
    - '--split-per-abi'
    - '--build-name'
    - '0.0.0'
    - '--build-number'
    - '0'
    - '--obfuscate'
    - '--split-debug-info'
    - 'packagex-build-debug'
  dart_compile_exe_arguments:
    - '--save-debugging-info=packagex-compile-debug'
  uploads:
    - platform_type: 'github'
      github_username: 'General-Developer'
      github_tag: 'release'
      github_is_org: true
      github_repository_name: 'llama_library'
  packages:
    - dart_target: 'llama_app'
      flutter_target: 'main'
      dart_name: 'llama_app'
      flutter_name: 'llama_app'
      output_name: 'llama-app'
msix_config:
  display_name: 'llama_app'
  install_certificate: false
